version: '3.7'

services:

    redis:
        restart: unless-stopped
        image: redis:latest
        ports:
            - 6379:6379
        container_name: redis
        volumes:
            - ./data/redis:/data
        command: ["redis-server", "--appendonly", "yes","--requirepass","WI4p82wr0i3cSwn0"]

    redis-commander:
        restart: unless-stopped
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOST=redis
            - REDIS_PASSWORD=WI4p82wr0i3cSwn0
            - HTTP_USER=root
            - HTTP_PASSWORD=com.root.admin.123
        ports:
            - 56379:8081
        depends_on:
            - redis

    mysql:
        restart: unless-stopped
        image: mysql:8.0.22
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./mysql/root:/root:ro
        environment:
            - MYSQL_ROOT_PASSWORD=gRrcYm07lj7Q
            - MYSQL_DATABASE=really_vpn

    phpmyadmin:
        restart: unless-stopped
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '53306:80'
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mysql

    mongo1:
        hostname: mongo1
        container_name: mongo-master
        image: mongo:4.0-xenial
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: gRrcYm07lj7Q
            MONGO_INITDB_DATABASE: admin
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
            - ./mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 400
            - ./mongo/root:/root:ro
            - ./data/mongo/volume:/data/db
            - ./data/mongo/config:/data/configdb
        entrypoint: [ "/usr/bin/mongod", "--auth", "--keyFile", "/etc/mongod-keyfile", "--bind_ip_all", "--replSet", "rs0" ]
        depends_on:
          - mongo2
          - mongo3
        
    mongo2:
        hostname: mongo2
        container_name: mongo-salve
        image: mongo:4.0-xenial
        restart: unless-stopped
        expose:
            - 27017
        ports:
            - 27018:27017
        volumes:
            - ./mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 400
        entrypoint: [ "/usr/bin/mongod", "--auth", "--keyFile", "/etc/mongod-keyfile", "--bind_ip_all", "--replSet", "rs0" ]
        depends_on:
          - mongo3

    mongo3:
        hostname: mongo3
        container_name: mongo-arbiter
        image: mongo:4.0-xenial
        restart: unless-stopped
        expose:
            - 27017
        ports:
            - 27019:27017
        volumes:
            - ./mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 400
        entrypoint: [ "/usr/bin/mongod", "--auth", "--keyFile", "/etc/mongod-keyfile", "--bind_ip_all", "--replSet", "rs0" ]

    mongo-express:
        container_name: mongo-express
        image: mongo-express:0.49.0
        restart: unless-stopped
        ports:
            - 57017:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: 'mongo1'
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: gRrcYm07lj7Q

            
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: com.root.admin.123
        depends_on:
          - mongo1
          - mongo2
          - mongo3

